# Generated by Django 5.2.4 on 2025-08-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0019_booking_booked_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (alternative to file upload)', null=True),
        ),
    ]
