# Generated by Django 5.2.4 on 2025-08-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_api', '0020_bike_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='bikes'),
        ),
    ]
